# Generated by Django 2.2 on 2019-04-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_api', '0002_auto_20190411_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_data',
            field=models.TextField(unique=True),
        ),
    ]
