# Generated by Django 2.2 on 2019-04-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_api', '0003_auto_20190412_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_data',
            field=models.TextField(),
        ),
    ]
