# Generated by Django 2.2 on 2019-04-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_api', '0005_auto_20190412_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(help_text='Title of the movie', max_length=200, unique=True),
        ),
    ]
