# Generated by Django 2.2 on 2019-04-13 19:39

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_api', '0006_auto_20190412_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 4, 13, 21, 39, 49, 27023), help_text='Date of comment posting'),
        ),
    ]
