# Generated by Django 2.2 on 2019-04-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_api', '0007_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(auto_now_add=True, help_text='Date of comment posting'),
        ),
    ]
